[general]
network_check_url = http://223.6.6.6
server_check_url = http://1.0.0.1/generate_204
server_check_timeout = 5000
profile_img_url= https://raw.githubusercontent.com/yuk1uno/image-cloud/main/icon/photo_2024-05-28_18-12-10.jpg
dns_exclusion_list=*.cmpassport.com, *.jegotrip.com.cn, *.icitymobile.mobi, id6.me, *.pingan.com.cn, *.cmbchina.com
geo_location_checker=http://ip-api.com/json/?lang=zh-CN, https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/scripts/server_location.js
resource_parser_url=https://raw.githubusercontent.com/KOP-XIAO/QuantumultX/master/Scripts/resource-parser.js
