//作者 https://t.me/yuk1shiro
// @Updatetime 2024/5/29 UTC/GMT +0


[General]
skip-proxy = 192.168.0.0/24, 10.0.0.0/8, 172.16.0.0/12, 127.0.0.1, localhost, *.local
exclude-simple-hostnames = true
internet-test-url = http://223.6.6.6
proxy-test-url = http://1.0.0.1/generate_204
test-timeout = 5
dns-server = 223.5.5.5, 114.114.114.114
# encrypted-dns-server = https://223.5.5.5/ // 除非当地 ISP 有严重的 DNS 污染问题，否则没必要开启 DoH，传统 DNS 的性能最优，网络异常后恢复速度最快
wifi-assist = true
ipv6 = false
ipv6-vif = disabled

[Proxy]

[Proxy Group]
Proxy = select, 香港, 台湾, 日本, 韩国, 新加坡, 美国,荷兰, no-alert=0, hidden=0, include-all-proxies=0
美国 = smart, no-alert=0, hidden=0, include-all-proxies=0, update-interval=0, policy-regex-filter=(🇺🇸)|(States)|(US)|(美国)|(美國),include-other-group=全部节点
香港 = smart, no-alert=0, hidden=0, include-all-proxies=0, update-interval=0, policy-regex-filter=(🇭🇰)|(港)|(香港)|(HK)|(Hong), include-other-group=全部节点
台湾 = smart, no-alert=0, hidden=0, include-all-proxies=0, update-interval=0, policy-regex-filter=(🇹🇼)|(台)|(Tai)|(TW)|(台湾)|(台灣), include-other-group=全部节点
日本 = smart, no-alert=0, hidden=0, include-all-proxies=0, update-interval=0, policy-regex-filter=(🇯🇵)|(Japan)|(JP)|(日本), include-other-group=全部节点
新加坡 = smart, no-alert=0, hidden=0, include-all-proxies=0, update-interval=0, policy-regex-filter=(🇸🇬)|(坡)|(Singapore)|(SG)|(狮城), include-other-group=全部节点
韩国 = smart, no-alert=0, hidden=0, include-all-proxies=0, update-interval=0, policy-regex-filter=(🇰🇷)|(韩)|(KR)|(韓國)|(韩国), include-other-group=全部节点
荷兰 = smart, no-alert=0, hidden=0, include-all-proxies=0, update-interval=0, policy-regex-filter=(🇳🇱)|(荷)|(荷兰)|(NL)|(荷蘭)|(阿姆斯特丹), include-other-group=全部节点
全部节点 = select, update-interval=0, no-alert=0, hidden=1, include-all-proxies=0, policy-path=机场链接


[Rule]
PROTOCOL,STUN,REJECT
# 去广告
RULE-SET,https://raw.githubusercontent.com/Centralmatrix3/Scripts/master/Surge/ruleset/AdBlock.list,REJECT
# Openai
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/OpenAI/OpenAI.list,美国
# Telegram 服务
IP-ASN,59930,美国,no-resolve // 𝙏𝙚𝙡𝙚𝙜𝙧𝙖𝙢 𝘿𝘾1
IP-ASN,44907,荷兰,no-resolve // 𝙏𝙚𝙡𝙚𝙜𝙧𝙖𝙢 𝘿𝘾2
IP-ASN,211157,美国,no-resolve // 𝙏𝙚𝙡𝙚𝙜𝙧𝙖𝙢 𝘿𝘾3
IP-ASN,62041,荷兰,no-resolve // 𝙏𝙚𝙡𝙚𝙜𝙧𝙖𝙢 𝘿𝘾4
IP-ASN,62014,新加坡,no-resolve // 𝙏𝙚𝙡𝙚𝙜𝙧𝙖𝙢 𝘿𝘾5
# 老刘的配置（老刘用 那我也用）
RULE-SET,https://github.com/Blankwonder/surge-list/raw/master/blocked.list,Proxy
RULE-SET,https://github.com/Blankwonder/surge-list/raw/master/cn.list,DIRECT
DOMAIN,apps.apple.com,Proxy
DOMAIN-SUFFIX,ls.apple.com,DIRECT // Apple Maps
DOMAIN-SUFFIX,store.apple.com,DIRECT // Apple Store Online
RULE-SET,SYSTEM,Proxy
RULE-SET,https://github.com/Blankwonder/surge-list/raw/master/apple.list,Proxy
# 以下规则将触发本地 DNS 解析
RULE-SET,LAN,DIRECT
GEOIP,CN,DIRECT
FINAL,Proxy,dns-failed
