// 作者 https://t.me/yuk1shiro
// @Updatetime 2024/10/12 UTC/GMT +8


[General]
skip-proxy = 192.168.0.0/24, 10.0.0.0/8, 172.16.0.0/12, 127.0.0.1, localhost, *.local
exclude-simple-hostnames = true
internet-test-url = http://223.6.6.6
proxy-test-url = http://1.0.0.1/generate_204
test-timeout = 5
dns-server = 223.5.5.5, 114.114.114.114
encrypted-dns-server = quic://dns.alidns.com/dns-query
wifi-assist = true
ipv6 = false
ipv6-vif = disabled
allow-wifi-access = true
http-api = Yuki@127.0.0.1:1123
http-api-tls = false
http-api-web-dashboard = true
udp-policy-not-supported-behaviour = REJECT

[Proxy]

[Proxy Group]
Proxy = select, 香港, 台湾, 日本, 韩国, 新加坡, 美国,荷兰, no-alert=0, hidden=0, include-all-proxies=0
Telegram = select, 香港, 台湾, 日本, 韩国, 新加坡, 美国,荷兰, no-alert=0, hidden=0, include-all-proxies=0
美国 = url-test, no-alert=0, hidden=0, include-all-proxies=0, update-interval=0, policy-regex-filter=(🇺🇸)|(States)|(US)|(美国)|(美國),include-other-group=全部节点
香港 = url-test, no-alert=0, hidden=0, include-all-proxies=0, update-interval=0, policy-regex-filter=(🇭🇰)|(港)|(香港)|(HK)|(Hong), include-other-group=全部节点
台湾 = url-test, no-alert=0, hidden=0, include-all-proxies=0, update-interval=0, policy-regex-filter=(🇹🇼)|(台)|(Tai)|(TW)|(台湾)|(台灣), include-other-group=全部节点
日本 = url-test, no-alert=0, hidden=0, include-all-proxies=0, update-interval=0, policy-regex-filter=(🇯🇵)|(Japan)|(JP)|(日本), include-other-group=全部节点
新加坡 = url-test, no-alert=0, hidden=0, include-all-proxies=0, update-interval=0, policy-regex-filter=(🇸🇬)|(坡)|(Singapore)|(SG)|(狮城), include-other-group=全部节点
韩国 = url-test, no-alert=0, hidden=0, include-all-proxies=0, update-interval=0, policy-regex-filter=(🇰🇷)|(韩)|(KR)|(韓國)|(韩国), include-other-group=全部节点
荷兰 = url-test, no-alert=0, hidden=0, include-all-proxies=0, update-interval=0, policy-regex-filter=(🇳🇱)|(荷)|(荷兰)|(NL)|(荷蘭)|(阿姆斯特丹), include-other-group=全部节点
全部节点 = select, update-interval=0, no-alert=0, hidden=0, include-all-proxies=0, policy-path=机场链接


[Rule]
OR,((PROTOCOL,STUN), (RULE-SET,https://adrules.top/adrules.list)),REJECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/OpenAI/OpenAI.list,美国 // openai
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Telegram/Telegram.list,Telegram // 以免有笨蛋
RULE-SET,https://github.com/Blankwonder/surge-list/raw/master/apple.list,Proxy // apple服务走代理才能最快
RULE-SET,LAN,DIRECT
GEOIP,CN,DIRECT
FINAL,Proxy,dns-failed
